# this is a configuration file for cruiseTrack2kml program

cruise      = "PIRATA-FR26"
ship        = "THALASSA"
callsign    = "FNFP"
begin_date  = 2016-03-08T08:00:00Z
end_date    = 2016-04-14T07:00:00Z
#begin_date  = "08/03/2016"
#end_date    = "14/04/2016"
institute      = "IRD"
pi             = "BOURLES"
creator        = "Jacques.Grelet_at_ird.fr"


[files]

  # You can indent as you please. Tabs or spaces. TOML don't care.
  [files.ctd]
  filename = "../ascii/pirata-fr26.ctd"
  skipline = 2
  varlist = "PRFL,1,BEGIN_DATE,2,BEGIN_TIME,3,END_DATE,4,END_TIME,5,LAT,6,LAT_S,7,LON,8,LON_S,9,TYPE_CAST,-1,PMAX,10,BOTTOM_DEPTH,11"
  plotnames = "http://www.brest.ird.fr/us191/cruises/pirata-fr26/dfr26%s.jpg"
  plotsize = 700
  prefix = 3
 
  [files.tsg]
  filename = "./data/fr26/ascii/pirata-fr26.gps"
  skipline = 2
  varlist = "LATITUDE,2,LONGITUDE,3"
  plotNames = "http://www.brest.ird.fr/us191/cruises/pirata-fr26/PIRATA-FR26_TSG_SCATTER.png"
  plotsize = 700


[kml]
filename = "pirata-fr26.kml"

